ARG FEDORA_VERSION=39
FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION}

RUN --mount=type=cache,target=/var/cache/dnf,z \
	dnf copr enable -y atim/starship

ARG GIT_REVISION=dirty
ARG GIT_REPO=unknown
ARG CONTAINERFILE_SOURCE=unknown

LABEL org.opencontainers.image.url=$GIT_REPO
LABEL org.opencontainers.image.source=$CONTAINERFILE_SOURCE
LABEL org.opencontainers.image.revision=$GIT_REVISION
