ARG FEDORA_VERSION=44
FROM quay.io/zzlotnik/toolbox:workspace-fedora-${FEDORA_VERSION} AS base
RUN --mount=type=cache,target=/var/cache/dnf,z \
  --mount=type=cache,target=/var/cache/libdnf5,z \
  dnf install -y cargo rust-analyzer && \
	find / -name "__pycache__" -type d | xargs rm -rf
