ARG FEDORA_VERSION=42
FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION}

RUN --mount=type=cache,target=/var/cache/dnf,z \
    --mount=type=cache,target=/root/.npm,z \
  dnf install -y nodejs-npm && \
  npm install -g @anthropic-ai/claude-code
