ARG FEDORA_VERSION=40
FROM quay.io/zzlotnik/toolbox:kube-fedora-${FEDORA_VERSION} AS base

FROM quay.io/zzlotnik/toolbox:tools-fetcher AS tools-fetcher

# FROM quay.io/zzlotnik/toolbox:cluster-debug-tools AS cluster-debug-tools

FROM base AS final
COPY --from=tools-fetcher /helpers/* /usr/local/bin/
# COPY --from=cluster-debug-tools /cluster-debug-tools /usr/local/bin/
