ARG FEDORA_VERSION=42
FROM quay.io/zzlotnik/toolbox:base-fedora-${FEDORA_VERSION} AS base

FROM base AS final
ARG FEDORA_VERSION=${FEDORA_VERSION}
COPY ./goreleaser.repo /etc/yum.repos.d/goreleaser.repo
RUN --mount=type=cache,target=/var/cache/dnf,z \
	dnf install --setopt=keepcache=True -y \
		docker \
		goreleaser \
		golang \
		golangci-lint \
		make \
		python3
