FROM quay.io/fedora/fedora:latest
RUN --mount=type=cache,target=/var/cache/dnf,z \
    dnf install -y fedora-workstation-repositories && \
    dnf config-manager setopt google-chrome.enabled=1 && \
    dnf install -y google-chrome-stable
