# This Containerfile is used to bring up an MCP (Model Context Protocol) server
# for interfacing with omc (OpenShift Must-Gather inspector) and with Claude
# Code, Gemini CLI and / or goose CLI.
ARG FEDORA_VERSION=42
FROM docker.io/library/golang:latest AS build-mcp-server
WORKDIR /mcp-server
RUN git clone --depth=1 https://github.com/shivprakashmuley/mustgather-mcp-server.git . && \
  go build -o /mcp-server/mustgather-mcp-server

ARG FEDORA_VERSION=42
FROM quay.io/fedora/fedora:${FEDORA_VERSION} AS fetch-omc
WORKDIR /omc
RUN --mount=type=cache,target=/var/cache/dnf,z \
    dnf install -y --setopt=keepcache=True jq && \
    curl -sL https://api.github.com/repos/gmeghnag/omc/releases/latest | jq -r '.assets[] | select(.name? | match("omc_Linux_x86_64.tar.gz$")) | .browser_download_url' > "download_url.txt" && \
    curl -L "$(cat download_url.txt)" | tar zx && \
    rm download_url.txt

ARG FEDORA_VERSION=42
FROM quay.io/zzlotnik/toolbox:ai-workspace-fedora-${FEDORA_VERSION}
COPY --from=build-mcp-server /mcp-server/mustgather-mcp-server /usr/bin/mustgather-mcp-server
COPY --from=fetch-omc /omc/omc /usr/bin/omc
