FROM quay.io/fedora/fedora-silverblue:39 AS base

FROM quay.io/zzlotnik/toolbox:tools AS tools
RUN --mount=type=cache,target=/var/cache/dnf,z \
	dnf copr enable -y atim/starship

FROM base AS final
COPY --from=tools /etc/yum.repos.d /etc/yum.repos.d
COPY --from=tools /yq/yq /usr/local/bin/yq
RUN --mount=type=cache,target=/var/cache/rpm-ostree,z \
	rpm-ostree install -y \
		bat \
		btop \
		curl \
		eza \
		fd-find \
		fzf \
		gh \
		git \
		git-delta \
		gpg \
		hyperfine \
		jq \
		langpacks-en \
		pinentry \
		ripgrep \
		skopeo \
		starship \
		tmux \
		zsh && \
	# Not removing these files prevents the eza alias from working
	rm /etc/profile.d/color*.csh /etc/profile.d/color*.sh && \
	ostree container commit

ARG GIT_REVISION=dirty
ARG GIT_REPO=unknown
ARG CONTAINERFILE_NAME=unknown

LABEL org.opencontainers.image.url=$GIT_REPO
LABEL org.opencontainers.image.source=$GIT_REPO
LABEL org.opencontainers.image.revision=$GIT_REVISION
LABEL containerfile_name=$CONTAINERFILE_NAME
