ARG FEDORA_VERSION=39
FROM quay.io/fedora/fedora-coreos:stable AS base

FROM quay.io/zzlotnik/toolbox:tools-fetcher AS tools-fetcher

FROM quay.io/zzlotnik/toolbox:copr-fedora-${FEDORA_VERSION} AS copr

FROM base AS final
COPY --from=copr /etc/yum.repos.d/_copr* /etc/yum.repos.d/
COPY --from=tools-fetcher /yq/yq /usr/local/bin/yq
RUN --mount=type=cache,target=/var/cache/rpm-ostree,z \
	rpm-ostree install -y \
		bat \
		btop \
		curl \
		eza \
		fd-find \
		fzf \
		git \
		git-delta \
		hyperfine \
		jq \
		langpacks-en \
		# One of my zsh plugins needs lua. I don't know why or what the plugin does, but I will humor it for now.
		lua \
		nvtop \
		ripgrep \
		skopeo \
		starship \
		tmux \
		zsh && \
	# Not removing these files prevents the eza alias from working
	rm /etc/profile.d/color*.csh /etc/profile.d/color*.sh && \
	ostree container commit

ARG GIT_REVISION=dirty
ARG GIT_REPO=unknown
ARG CONTAINERFILE_SOURCE=unknown

LABEL org.opencontainers.image.url=$GIT_REPO
LABEL org.opencontainers.image.source=$CONTAINERFILE_SOURCE
LABEL org.opencontainers.image.revision=$GIT_REVISION
