FROM quay.io/fedora/fedora-toolbox:44 AS prep
WORKDIR /usr/local/bin
RUN curl 'https://raw.githubusercontent.com/devmatteini/dra/refs/heads/main/install.sh' | /bin/bash
COPY install.sh /tmp/install.sh
COPY get-arch.py /usr/local/bin/get-arch

FROM prep AS install
RUN /tmp/install.sh

FROM quay.io/zzlotnik/zacks-openshift-helpers:latest AS helpers

FROM scratch AS final
COPY --from=helpers /usr/local/bin/rcctl /usr/local/bin/rcctl
COPY --from=install /usr/local/bin/ /usr/local/bin/
