FROM docker.io/library/golang:latest AS builder
WORKDIR /mco
ENV GOCACHE="/go/.cache"
ENV GOMODCACHE="/go/pkg/mod"
RUN --mount=type=cache,target=/go/.cache,z \
    --mount=type=cache,target=/go/pkg/mod,z \
    git clone --depth=1 https://github.com/openshift/machine-config-operator.git . && \
    make -j install-helpers

FROM quay.io/fedora/fedora:42 AS final
COPY --from=builder /mco/_output/linux/amd64/ /usr/local/bin/
