ARG FEDORA_VERSION=39
FROM quay.io/fedora/fedora-silverblue:${FEDORA_VERSION} AS base

ARG FEDORA_VERSION=39
FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION} AS copr
RUN --mount=type=cache,target=/var/cache/,z \
	dnf copr enable -y atim/starship && \
	dnf copr enable -y gmaglione/podman-bootc

FROM quay.io/zzlotnik/toolbox:tools-fetcher AS tools-fetcher

FROM base AS final
COPY --from=copr /etc/yum.repos.d/_copr* /etc/yum.repos.d/
COPY --from=tools-fetcher /yq/yq /usr/local/bin/yq
RUN --mount=type=cache,target=/var/cache/rpm-ostree,z \
	rpm-ostree install -y \
		bat \
		btop \
		crun-vm \
		curl \
		eza \
		fd-find \
		fzf \
		git \
		git-delta \
		hyperfine \
		jq \
		langpacks-en \
		# One of my zsh plugins needs lua. I don't know why or what the plugin does, but I will humor it for now.
		kitty \
		lua \
		nvtop \
		podman-bootc \
		# qflipper cannot be run from a toolbox container
		qflipper \
		ripgrep \
		skopeo \
		starship \
		tmux \
		# Needed to let crun-vm work.
		qemu-system-x86 \
		zsh && \
	# Not removing these files prevents the eza alias from working
	rm /etc/profile.d/color*.csh /etc/profile.d/color*.sh && \
	ostree container commit
