FROM quay.io/zzlotnik/toolbox:tools AS tools

FROM registry.fedoraproject.org/fedora:latest AS final
RUN --mount=type=cache,target=/var/cache/dnf,z \
	dnf install -y openssh-clients
COPY --from=tools /yq/yq /usr/local/bin/yq

ARG GIT_REVISION=dirty
ARG GIT_REPO=unknown
ARG CONTAINERFILE_NAME=unknown

LABEL org.opencontainers.image.url=$GIT_REPO
LABEL org.opencontainers.image.source=$GIT_REPO
LABEL org.opencontainers.image.revision=$GIT_REVISION
LABEL containerfile_name=$CONTAINERFILE_NAME
