FROM quay.io/zzlotnik/toolbox:tools-fetcher AS tools-fetcher

FROM quay.io/fedora/fedora:42 AS final
RUN --mount=type=cache,target=/var/cache/dnf,z \
	dnf install -y --setopt=keepcache=True openssh-clients
COPY --from=tools-fetcher /usr/local/bin/yq /usr/local/bin/yq
